
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-gauchoride-w24-7pm-1
owner: ucsb-cs156-w24
repo_name: proj-gauchoride-w24-7pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjgyNzc3NDU2","is_bot":false,"login":"liamlizard","name":""},"headRefName":"LR-DriverAvailabilityController","number":38,"title":"LR Added Driver Availability Controller with POST (new) and GET (admin all) with Tests","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/38"},{"author":{"id":"U_kgDOB09jxQ","is_bot":false,"login":"Daoyijiucsb","name":"Daoyi"},"headRefName":"dj-showapply-noedit","number":37,"title":"Added the RiderApplicationShowPage","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/37"},{"author":{"id":"MDQ6VXNlcjkxMzkxMTEx","is_bot":false,"login":"jamespflaging","name":"James Pflaging"},"headRefName":"James-driver-availaibilty-db-record-fixtures","number":35,"title":"James - Add DB record and fixtures for Driver Availability","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/35"}]
