
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-gauchoride-w24-7pm-1
owner: ucsb-cs156-w24
repo_name: proj-gauchoride-w24-7pm-1
pull_requests: [{"author":{"id":"U_kgDOBbk9KA","is_bot":false,"login":"owenjpark","name":"Owen Park"},"headRefName":"OP-AdminAssignDriver2","number":44,"title":"OP - EPIC: Admins can assign drivers to rides #95","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/44"},{"author":{"id":"MDQ6VXNlcjgyNzc3NDU2","is_bot":false,"login":"liamlizard","name":""},"headRefName":"LR-DriverAvailabilityController","number":42,"title":"LR driver availability controller","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/42"},{"author":{"id":"U_kgDOB3Dehg","is_bot":false,"login":"Ze-el","name":"Zeel Patel"},"headRefName":"zp-EPIC-gauchorideService-6","number":41,"title":"ZP - Added Rider Application Tables for Admin's to review","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/41"},{"author":{"id":"U_kgDOBXd_vw","is_bot":false,"login":"gretchenlam","name":""},"headRefName":"Gretchen-DriverAvailabilityForm","number":39,"title":"Add Driver Availability Form + Tests","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/39"}]
