
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-gauchoride-w24-7pm-1
owner: ucsb-cs156-w24
repo_name: proj-gauchoride-w24-7pm-1
pull_requests: [{"author":{"id":"U_kgDOBXd_vw","is_bot":false,"login":"gretchenlam","name":""},"headRefName":"Gretchen-DriverAvailabilityForm","number":39,"title":"Add Driver Availability Form + Tests","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/39"},{"author":{"id":"MDQ6VXNlcjgyNzc3NDU2","is_bot":false,"login":"liamlizard","name":""},"headRefName":"LR-DriverAvailabilityController","number":38,"title":"LR Added Driver Availability Controller with POST (new) and GET (admin all) with Tests","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/38"}]
