
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-gauchoride-w24-7pm-1
owner: ucsb-cs156-w24
repo_name: proj-gauchoride-w24-7pm-1
pull_requests: [{"author":{"id":"U_kgDOBXd_vw","is_bot":false,"login":"gretchenlam","name":""},"headRefName":"Gretchen-DriverAvailabilityAdminPages","number":51,"title":"Add DriverAvailability Index Page for Admin User","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/51"},{"author":{"id":"MDQ6VXNlcjkxMzkxMTEx","is_bot":false,"login":"jamespflaging","name":"James Pflaging"},"headRefName":"James-DriverAvailabilityPages","number":50,"title":"James - Driver Availability Pages, Stories","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/50"},{"author":{"id":"U_kgDOB09jxQ","is_bot":false,"login":"Daoyijiucsb","name":"Daoyi"},"headRefName":"dj-applyshow-limit","number":49,"title":"Limit the displayed element in the ShowRiderApplyPage","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/49"},{"author":{"id":"U_kgDOB3Dehg","is_bot":false,"login":"Ze-el","name":"Zeel Patel"},"headRefName":"zp-EPIC-gauchorideService-6-part2","number":46,"title":"ZP - Added Rider Application Buttons to Change the Status","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/46"},{"author":{"id":"U_kgDOB3Dehg","is_bot":false,"login":"Ze-el","name":"Zeel Patel"},"headRefName":"zp-EPIC-driver-availability-4","number":45,"title":"ZP - Driver Availability Table and Tests","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/45"},{"author":{"id":"U_kgDOBbk9KA","is_bot":false,"login":"owenjpark","name":"Owen Park"},"headRefName":"OP-AdminAssignDriver2","number":44,"title":"OP - EPIC: Admins can assign drivers to rides #95","url":"https://github.com/ucsb-cs156-w24/proj-gauchoride-w24-7pm-1/pull/44"}]
